In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv(" #RIPKobe4.4.csv")
data.head()

,text,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,"Love you, Mamba. #RIPKobe https://t.co/5yOHhU8d7c",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,I'm watching Kobe's final game. I know exactly...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Watching Kobe's Farewell game and I'm still ge...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Bro, one thing about Kobe.....he ALWAYS had th...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Kobe, Duncan and Garnett what a HOF class!!! L...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
text = data["text"]

In [13]:
text

0      Love you, Mamba. #RIPKobe https://t.co/5yOHhU8d7c
1      I'm watching Kobe's final game. I know exactly...
2      Watching Kobe's Farewell game and I'm still ge...
3      Bro, one thing about Kobe.....he ALWAYS had th...
4      Kobe, Duncan and Garnett what a HOF class!!! L...
                             ...
474    Ok #ripkobe ‚ù§ but I'm sorry I'm picking #2 and...
475    I really miss Kobe man......... üíúüíõ üêê 8 üêê 24 #N...
476    Just watched 3 random episodes of Deal and No ...
477    Nah fam, I hate it here. Fuck 2020. #WW3Scare ...
478    @KendrickPerkins @stephenasmith @Espngreeny Al...
Name: text, Length: 479, dtype: object

In [14]:
import preprocessor as p

In [15]:
def preprocess_tweet(row):
    text = row['text']
    text = p.clean(text)
    return text

In [16]:
data['text'] = data.apply(preprocess_tweet, axis=1)

In [17]:
data.head()

,text,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,"Love you, Mamba.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,I'm watching Kobe's final game. I know exactly...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Watching Kobe's Farewell game and I'm still ge...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Bro, one thing about Kobe.....he ALWAYS had th...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Kobe, Duncan and Garnett what a HOF class!!! L...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
from gensim.parsing.preprocessing import remove_stopwords

In [19]:
def stopword_removal(row):
    text = row['text']
    text = remove_stopwords(text)
    return text

In [20]:
data['text'] = data.apply(stopword_removal, axis=1)

In [21]:
data.head()

,text,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,"Love you, Mamba.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,I'm watching Kobe's final game. I know exactly...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Watching Kobe's Farewell game I'm getting chil...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Bro, thing Kobe.....he ALWAYS swag. Iykyk",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Kobe, Duncan Garnett HOF class!!! Legends!! ‚Ä¶",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
tweets = data['text']

In [23]:
tweets

0                                       Love you, Mamba.
1      I'm watching Kobe's final game. I know exactly...
2      Watching Kobe's Farewell game I'm getting chil...
3              Bro, thing Kobe.....he ALWAYS swag. Iykyk
4          Kobe, Duncan Garnett HOF class!!! Legends!! ‚Ä¶
                             ...
474    Ok I'm sorry I'm picking kicking dumbass kanye...
475                             I miss Kobe man.........
476    Just watched random episodes Deal No Deal And ...
477                         Nah fam, I hate here. Fuck .
478    All said "reminds". Y'all act like brotha call...
Name: text, Length: 479, dtype: object

In [26]:
tweets.to_csv ('KobeDataClean.csv', index = False, header=True)